server:
  port: 9092
#  #设置服务名
#  servlet:
#    context-path: /dailypaper
spring:
  application:
    name: User Server
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/DailyPaper
    username: postgres
    password: passwd
    driver-class-name: org.postgresql.Driver
# application:
#  name: hello-service
  #设置服务注册中心的URL，本服务要向该服务注册中心注册自己
#eureka:
# client:
#   serviceUrl:
#     defaultZone: http://192.168.100.243:9000/eureka
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.jackson.user.orm.mapper



eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka

